name: Run BDD Tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      HEADLESS: "true"
      BROWSER: "chrome"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install pipenv
      run: pip install pipenv
    
    - name: Install dependencies
      run: pipenv install
    
    - name: Run tests
      run: pipenv run python -m pytest tests/step_defs/ -v
